'use strict';

/**
 * Core Game V1 Word Database
 *
 * Rules:
 * - Approximately 300 words (8 categories x ~37 words each = 296 words).
 * - Easy and Medium difficulty only.
 * - Structured metadata: word, category, difficulty, aliases, forbiddenVariants, compoundVariants, notes.
 */

const WORDS = {
  "Animals & Wildlife": [
    { word: "Elephant", category: "Animals & Wildlife", difficulty: "easy", aliases: ["elephants"], forbiddenVariants: ["trunked", "ivory"], compoundVariants: ["pachyderm"], notes: "Savanna giant" },
    { word: "Giraffe", category: "Animals & Wildlife", difficulty: "easy", aliases: ["giraffes"], forbiddenVariants: ["longneck"], compoundVariants: [], notes: "Tallest mammal" },
    { word: "Penguin", category: "Animals & Wildlife", difficulty: "easy", aliases: ["penguins"], forbiddenVariants: ["tuxedo bird"], compoundVariants: [], notes: "Flightless seabird" },
    { word: "Dolphin", category: "Animals & Wildlife", difficulty: "easy", aliases: ["dolphins"], forbiddenVariants: ["porpoise"], compoundVariants: [], notes: "Playful ocean mammal" },
    { word: "Kangaroo", category: "Animals & Wildlife", difficulty: "easy", aliases: ["kangaroos", "roos"], forbiddenVariants: ["joey", "marsupial"], compoundVariants: [], notes: "Pouch hopper" },
    { word: "Zebra", category: "Animals & Wildlife", difficulty: "easy", aliases: ["zebras"], forbiddenVariants: ["striped horse"], compoundVariants: [], notes: "Striped equinoid" },
    { word: "Octopus", category: "Animals & Wildlife", difficulty: "medium", aliases: ["octopuses", "octopi"], forbiddenVariants: ["eight tentacle"], compoundVariants: [], notes: "Cephalopod" },
    { word: "Cheetah", category: "Animals & Wildlife", difficulty: "medium", aliases: ["cheetahs"], forbiddenVariants: ["fastest cat"], compoundVariants: [], notes: "Fast savanna sprinter" },
    { word: "Gorilla", category: "Animals & Wildlife", difficulty: "medium", aliases: ["gorillas"], forbiddenVariants: ["silverback"], compoundVariants: [], notes: "Largest living primate" },
    { word: "Crocodile", category: "Animals & Wildlife", difficulty: "medium", aliases: ["croc", "crocodiles"], forbiddenVariants: ["alligator", "swamp reptile"], compoundVariants: [], notes: "Armored river predator" },
    { word: "Flamingo", category: "Animals & Wildlife", difficulty: "medium", aliases: ["flamingos"], forbiddenVariants: ["pink bird"], compoundVariants: [], notes: "Wading pink waterbird" },
    { word: "Chameleon", category: "Animals & Wildlife", difficulty: "medium", aliases: ["chameleons"], forbiddenVariants: ["color change"], compoundVariants: [], notes: "Color-shifting lizard" },
    { word: "Platypus", category: "Animals & Wildlife", difficulty: "medium", aliases: ["platypuses"], forbiddenVariants: ["duck bill"], compoundVariants: [], notes: "Egg-laying mammal" },
    { word: "Hedgehog", category: "Animals & Wildlife", difficulty: "medium", aliases: ["hedgehogs"], forbiddenVariants: ["spiny ball"], compoundVariants: [], notes: "Spiny mammal" },
    { word: "Peacock", category: "Animals & Wildlife", difficulty: "medium", aliases: ["peacocks", "peafowl"], forbiddenVariants: ["fan feathers"], compoundVariants: [], notes: "Showy plumage bird" },
    { word: "Hippopotamus", category: "Animals & Wildlife", difficulty: "medium", aliases: ["hippo", "hippos"], forbiddenVariants: ["river horse"], compoundVariants: [], notes: "Heavy river herbivore" },
    { word: "Rhinoceros", category: "Animals & Wildlife", difficulty: "medium", aliases: ["rhino", "rhinos"], forbiddenVariants: ["horned beast"], compoundVariants: [], notes: "Horned herbivore" },
    { word: "Squirrel", category: "Animals & Wildlife", difficulty: "medium", aliases: ["squirrels"], forbiddenVariants: ["acorn collector"], compoundVariants: [], notes: "Bushy-tailed rodent" },
    { word: "Wolf", category: "Animals & Wildlife", difficulty: "easy", aliases: ["wolves"], forbiddenVariants: ["howler"], compoundVariants: [], notes: "Pack hunter canine" },
    { word: "Tiger", category: "Animals & Wildlife", difficulty: "easy", aliases: ["tigers"], forbiddenVariants: ["striped cat"], compoundVariants: [], notes: "Largest wild cat" },
    { word: "Lion", category: "Animals & Wildlife", difficulty: "easy", aliases: ["lions"], forbiddenVariants: ["king of jungle"], compoundVariants: [], notes: "Maned pride predator" },
    { word: "Bear", category: "Animals & Wildlife", difficulty: "easy", aliases: ["bears", "grizzly"], forbiddenVariants: ["hibernator"], compoundVariants: [], notes: "Forest carnivoran" },
    { word: "Rabbit", category: "Animals & Wildlife", difficulty: "easy", aliases: ["rabbits", "bunny"], forbiddenVariants: ["hare"], compoundVariants: [], notes: "Long-eared burrower" },
    { word: "Eagle", category: "Animals & Wildlife", difficulty: "medium", aliases: ["eagles"], forbiddenVariants: ["bird of prey"], compoundVariants: [], notes: "Raptor bird" },
    { word: "Beaver", category: "Animals & Wildlife", difficulty: "medium", aliases: ["beavers"], forbiddenVariants: ["dam builder"], compoundVariants: [], notes: "Timber chewing rodent" },
    { word: "Otter", category: "Animals & Wildlife", difficulty: "medium", aliases: ["otters"], forbiddenVariants: ["river slider"], compoundVariants: [], notes: "Sleek aquatic weasel" },
    { word: "Panda", category: "Animals & Wildlife", difficulty: "medium", aliases: ["pandas"], forbiddenVariants: ["bamboo bear"], compoundVariants: [], notes: "Bamboo eating bear" },
    { word: "Koala", category: "Animals & Wildlife", difficulty: "medium", aliases: ["koalas"], forbiddenVariants: ["eucalyptus bear"], compoundVariants: [], notes: "Tree clinging marsupial" },
    { word: "Shark", category: "Animals & Wildlife", difficulty: "easy", aliases: ["sharks"], forbiddenVariants: ["great white"], compoundVariants: [], notes: "Apex marine predator" },
    { word: "Turtle", category: "Animals & Wildlife", difficulty: "medium", aliases: ["turtles", "tortoise"], forbiddenVariants: ["shelled reptile"], compoundVariants: [], notes: "Hard-shelled crawler" },
    { word: "Camel", category: "Animals & Wildlife", difficulty: "medium", aliases: ["camels", "dromedary"], forbiddenVariants: ["desert humps"], compoundVariants: [], notes: "Humped desert traveler" },
    { word: "Falcon", category: "Animals & Wildlife", difficulty: "medium", aliases: ["falcons"], forbiddenVariants: ["peregrine"], compoundVariants: [], notes: "Fast diving raptor" },
    { word: "Parrot", category: "Animals & Wildlife", difficulty: "easy", aliases: ["parrots", "macaw"], forbiddenVariants: ["talking bird"], compoundVariants: [], notes: "Tropical mimic bird" },
    { word: "Badger", category: "Animals & Wildlife", difficulty: "medium", aliases: ["badgers"], forbiddenVariants: ["burrow fighter"], compoundVariants: [], notes: "Tough nocturnal burrower" },
    { word: "Walrus", category: "Animals & Wildlife", difficulty: "medium", aliases: ["walruses"], forbiddenVariants: ["tusked seal"], compoundVariants: [], notes: "Tusked marine mammal" },
    { word: "Pelican", category: "Animals & Wildlife", difficulty: "medium", aliases: ["pelicans"], forbiddenVariants: ["pouch beak"], compoundVariants: [], notes: "Throat pouch seabird" },
    { word: "Lobster", category: "Animals & Wildlife", difficulty: "medium", aliases: ["lobsters"], forbiddenVariants: ["clawed crustacean"], compoundVariants: [], notes: "Sea-floor crustacean" }
  ],

  "Food & Drink": [
    { word: "Pizza", category: "Food & Drink", difficulty: "easy", aliases: ["pizzas", "slice"], forbiddenVariants: ["pepperoni pie"], compoundVariants: [], notes: "Baked cheese crust round" },
    { word: "Burger", category: "Food & Drink", difficulty: "easy", aliases: ["burgers", "hamburger", "cheeseburger"], forbiddenVariants: ["patty on bun"], compoundVariants: [], notes: "Grilled patty bun sandwich" },
    { word: "Sushi", category: "Food & Drink", difficulty: "easy", aliases: ["sashimi", "nigiri"], forbiddenVariants: ["raw fish roll"], compoundVariants: [], notes: "Rolled vinegar rice dish" },
    { word: "Pancake", category: "Food & Drink", difficulty: "easy", aliases: ["pancakes", "flapjacks"], forbiddenVariants: ["griddle cake"], compoundVariants: [], notes: "Flat batter breakfast round" },
    { word: "Ramen", category: "Food & Drink", difficulty: "easy", aliases: ["ramen noodles"], forbiddenVariants: ["noodle broth"], compoundVariants: [], notes: "Japanese noodle soup" },
    { word: "Chocolate", category: "Food & Drink", difficulty: "easy", aliases: ["chocolates", "cocoa"], forbiddenVariants: ["cocoa bar"], compoundVariants: [], notes: "Sweet cacao treat" },
    { word: "Popcorn", category: "Food & Drink", difficulty: "easy", aliases: ["popped corn"], forbiddenVariants: ["movie corn"], compoundVariants: [], notes: "Puffed corn snack" },
    { word: "Coffee", category: "Food & Drink", difficulty: "easy", aliases: ["espresso", "latte", "cappuccino"], forbiddenVariants: ["caffeine brew"], compoundVariants: [], notes: "Roasted bean beverage" },
    { word: "Donut", category: "Food & Drink", difficulty: "easy", aliases: ["donuts", "doughnut"], forbiddenVariants: ["glazed ring"], compoundVariants: [], notes: "Fried dough ring" },
    { word: "Burrito", category: "Food & Drink", difficulty: "medium", aliases: ["burritos"], forbiddenVariants: ["wrapped tortilla"], compoundVariants: [], notes: "Rolled flour tortilla wrap" },
    { word: "Lasagna", category: "Food & Drink", difficulty: "medium", aliases: ["lasagne"], forbiddenVariants: ["layered pasta"], compoundVariants: [], notes: "Layered sheet pasta bake" },
    { word: "Cheesecake", category: "Food & Drink", difficulty: "medium", aliases: ["cheese cake"], forbiddenVariants: ["cream cheese pie"], compoundVariants: ["cheese cake"], notes: "Rich baked dessert slice" },
    { word: "Pretzel", category: "Food & Drink", difficulty: "medium", aliases: ["pretzels"], forbiddenVariants: ["twisted bread"], compoundVariants: [], notes: "Salted knot pastry" },
    { word: "Milkshake", category: "Food & Drink", difficulty: "medium", aliases: ["shake", "milkshakes"], forbiddenVariants: ["blended ice cream"], compoundVariants: ["milk shake"], notes: "Frothy ice cream drink" },
    { word: "Waffle", category: "Food & Drink", difficulty: "medium", aliases: ["waffles"], forbiddenVariants: ["grid cake"], compoundVariants: [], notes: "Patterned griddle batter" },
    { word: "Curry", category: "Food & Drink", difficulty: "medium", aliases: ["curries"], forbiddenVariants: ["spiced gravy"], compoundVariants: [], notes: "Aromatic spiced stew" },
    { word: "Dumpling", category: "Food & Drink", difficulty: "medium", aliases: ["dumplings", "potsticker"], forbiddenVariants: ["stuffed dough"], compoundVariants: [], notes: "Steamed or fried pocket" },
    { word: "Croissant", category: "Food & Drink", difficulty: "medium", aliases: ["croissants"], forbiddenVariants: ["flaky crescent"], compoundVariants: [], notes: "Buttery layered pastry" },
    { word: "Guacamole", category: "Food & Drink", difficulty: "medium", aliases: ["guac"], forbiddenVariants: ["mashed avocado"], compoundVariants: [], notes: "Avocado lime dip" },
    { word: "Muffin", category: "Food & Drink", difficulty: "medium", aliases: ["muffins"], forbiddenVariants: ["cup bread"], compoundVariants: [], notes: "Single-serving baked bread" },
    { word: "Omelet", category: "Food & Drink", difficulty: "medium", aliases: ["omelette", "omelets"], forbiddenVariants: ["folded eggs"], compoundVariants: [], notes: "Folded egg creation" },
    { word: "Smoothie", category: "Food & Drink", difficulty: "easy", aliases: ["smoothies"], forbiddenVariants: ["blended fruit"], compoundVariants: [], notes: "Puréed fruit beverage" },
    { word: "Nachos", category: "Food & Drink", difficulty: "easy", aliases: ["nacho"], forbiddenVariants: ["tortilla chips"], compoundVariants: [], notes: "Cheese covered tortilla chips" },
    { word: "Cupcake", category: "Food & Drink", difficulty: "easy", aliases: ["cupcakes"], forbiddenVariants: ["mini cake"], compoundVariants: ["cup cake"], notes: "Small frosted cake" },
    { word: "Spaghetti", category: "Food & Drink", difficulty: "easy", aliases: ["pasta strings"], forbiddenVariants: ["marinara noodles"], compoundVariants: [], notes: "Long wheat pasta cords" },
    { word: "Tacos", category: "Food & Drink", difficulty: "easy", aliases: ["taco"], forbiddenVariants: ["crisp shell"], compoundVariants: [], notes: "Folded tortilla packet" },
    { word: "Brownie", category: "Food & Drink", difficulty: "medium", aliases: ["brownies"], forbiddenVariants: ["fudge square"], compoundVariants: [], notes: "Fudge chocolate square" },
    { word: "Baguette", category: "Food & Drink", difficulty: "medium", aliases: ["french bread"], forbiddenVariants: ["crusty loaf"], compoundVariants: [], notes: "Long thin French loaf" },
    { word: "Sandwich", category: "Food & Drink", difficulty: "easy", aliases: ["sandwiches", "sammich"], forbiddenVariants: ["two bread slices"], compoundVariants: [], notes: "Bread with filling" },
    { word: "Mustard", category: "Food & Drink", difficulty: "medium", aliases: ["yellow mustard", "dijon"], forbiddenVariants: ["spicy seed condiment"], compoundVariants: [], notes: "Pungent seed condiment" },
    { word: "Salad", category: "Food & Drink", difficulty: "easy", aliases: ["salads"], forbiddenVariants: ["mixed greens"], compoundVariants: [], notes: "Tossed vegetable mixture" },
    { word: "Hotdog", category: "Food & Drink", difficulty: "easy", aliases: ["hot dog", "frankfurter"], forbiddenVariants: ["wiener on bun"], compoundVariants: ["hot dog"], notes: "Cured sausage on sliced bun" },
    { word: "Popsicle", category: "Food & Drink", difficulty: "easy", aliases: ["ice pop", "popsicles"], forbiddenVariants: ["frozen stick"], compoundVariants: ["ice pop"], notes: "Frozen juice on stick" },
    { word: "Sausage", category: "Food & Drink", difficulty: "medium", aliases: ["sausages", "bratwurst"], forbiddenVariants: ["cased ground meat"], compoundVariants: [], notes: "Minced seasoned meat roll" },
    { word: "Risotto", category: "Food & Drink", difficulty: "medium", aliases: ["creamy rice"], forbiddenVariants: ["arborio rice"], compoundVariants: [], notes: "Slow stirred Italian rice" },
    { word: "Barbecue", category: "Food & Drink", difficulty: "medium", aliases: ["bbq"], forbiddenVariants: ["smoked meat"], compoundVariants: [], notes: "Slow smoked seasoned meat" },
    { word: "Cereal", category: "Food & Drink", difficulty: "easy", aliases: ["cereals", "cornflakes"], forbiddenVariants: ["breakfast bowl with milk"], compoundVariants: [], notes: "Grain breakfast bowl" }
  ],

  "Everyday Objects": [
    { word: "Umbrella", category: "Everyday Objects", difficulty: "easy", aliases: ["umbrellas", "parasol"], forbiddenVariants: ["rain canopy"], compoundVariants: [], notes: "Foldable rain canopy" },
    { word: "Backpack", category: "Everyday Objects", difficulty: "easy", aliases: ["backpacks", "knapsack", "bookbag"], forbiddenVariants: ["shoulder bag"], compoundVariants: ["back pack"], notes: "Shoulder-strapped carrying pack" },
    { word: "Mirror", category: "Everyday Objects", difficulty: "easy", aliases: ["mirrors", "looking glass"], forbiddenVariants: ["reflective glass"], compoundVariants: [], notes: "Reflective silvered glass" },
    { word: "Scissors", category: "Everyday Objects", difficulty: "easy", aliases: ["shears"], forbiddenVariants: ["cutting blades"], compoundVariants: [], notes: "Pivoting double blades" },
    { word: "Toothbrush", category: "Everyday Objects", difficulty: "easy", aliases: ["tooth brush"], forbiddenVariants: ["dental bristle"], compoundVariants: ["tooth brush"], notes: "Bristled dental brush" },
    { word: "Flashlight", category: "Everyday Objects", difficulty: "easy", aliases: ["torch"], forbiddenVariants: ["handheld beam"], compoundVariants: ["flash light"], notes: "Portable electric lamp" },
    { word: "Pillow", category: "Everyday Objects", difficulty: "easy", aliases: ["pillows", "cushion"], forbiddenVariants: ["head cushion"], compoundVariants: [], notes: "Soft head rest cushion" },
    { word: "Blanket", category: "Everyday Objects", difficulty: "easy", aliases: ["blankets", "comforter", "quilt"], forbiddenVariants: ["warm fleece"], compoundVariants: [], notes: "Warm woven fabric throw" },
    { word: "Wallet", category: "Everyday Objects", difficulty: "easy", aliases: ["wallets", "billfold"], forbiddenVariants: ["pocket cash holder"], compoundVariants: [], notes: "Foldable pocket card holder" },
    { word: "Sunglasses", category: "Everyday Objects", difficulty: "easy", aliases: ["shades", "sun glasses"], forbiddenVariants: ["tinted eyewear"], compoundVariants: ["sun glasses"], notes: "Tinted lens protective eyewear" },
    { word: "Stapler", category: "Everyday Objects", difficulty: "medium", aliases: ["staplers"], forbiddenVariants: ["paper binder"], compoundVariants: [], notes: "Wire paper binding device" },
    { word: "Padlock", category: "Everyday Objects", difficulty: "medium", aliases: ["padlocks"], forbiddenVariants: ["shackled lock"], compoundVariants: ["pad lock"], notes: "Detachable shackle lock" },
    { word: "Thermometer", category: "Everyday Objects", difficulty: "medium", aliases: ["thermometers"], forbiddenVariants: ["temperature gauge"], compoundVariants: [], notes: "Temperature measuring device" },
    { word: "Compass", category: "Everyday Objects", difficulty: "medium", aliases: ["magnetic compass"], forbiddenVariants: ["needle pointer"], compoundVariants: [], notes: "Magnetic directional instrument" },
    { word: "Kettle", category: "Everyday Objects", difficulty: "medium", aliases: ["tea kettle", "kettles"], forbiddenVariants: ["water boiler"], compoundVariants: [], notes: "Spouted water boiling vessel" },
    { word: "Candle", category: "Everyday Objects", difficulty: "medium", aliases: ["candles"], forbiddenVariants: ["wax wick"], compoundVariants: [], notes: "Wax cylinder with central wick" },
    { word: "Notebook", category: "Everyday Objects", difficulty: "medium", aliases: ["journal", "notepad"], forbiddenVariants: ["bound lined paper"], compoundVariants: ["note book"], notes: "Bound lined pages for writing" },
    { word: "Sponge", category: "Everyday Objects", difficulty: "medium", aliases: ["sponges"], forbiddenVariants: ["porous scrubber"], compoundVariants: [], notes: "Porous absorbent scrubber" },
    { word: "Whistle", category: "Everyday Objects", difficulty: "medium", aliases: ["whistles"], forbiddenVariants: ["wind pipe sound"], compoundVariants: [], notes: "Air-blown sound pipe" },
    { word: "Toothpaste", category: "Everyday Objects", difficulty: "medium", aliases: ["tooth paste", "dentifrice"], forbiddenVariants: ["brush paste"], compoundVariants: ["tooth paste"], notes: "Minty cleansing paste for teeth" },
    { word: "Bicycle", category: "Everyday Objects", difficulty: "medium", aliases: ["bike", "bicycles"], forbiddenVariants: ["pedal two wheeler"], compoundVariants: [], notes: "Two-wheeled pedal vehicle" },
    { word: "Hanger", category: "Everyday Objects", difficulty: "medium", aliases: ["coat hanger", "hangers"], forbiddenVariants: ["closet hook"], compoundVariants: [], notes: "Wire or plastic garment frame" },
    { word: "Curtains", category: "Everyday Objects", difficulty: "medium", aliases: ["curtain", "drapes"], forbiddenVariants: ["window hanging"], compoundVariants: [], notes: "Window fabric hangings" },
    { word: "Vase", category: "Everyday Objects", difficulty: "medium", aliases: ["vases", "flower pot"], forbiddenVariants: ["flower vessel"], compoundVariants: [], notes: "Decorative flower jar" },
    { word: "Clock", category: "Everyday Objects", difficulty: "easy", aliases: ["clocks", "timepiece"], forbiddenVariants: ["time face"], compoundVariants: [], notes: "Dial or digital time tracker" },
    { word: "Chair", category: "Everyday Objects", difficulty: "easy", aliases: ["chairs", "seat"], forbiddenVariants: ["four legged seat"], compoundVariants: [], notes: "Individual seat with backrest" },
    { word: "Towel", category: "Everyday Objects", difficulty: "easy", aliases: ["towels"], forbiddenVariants: ["drying cloth"], compoundVariants: [], notes: "Absorbent drying fabric" },
    { word: "Suitcase", category: "Everyday Objects", difficulty: "easy", aliases: ["luggage", "suitcases"], forbiddenVariants: ["travel bag"], compoundVariants: ["suit case"], notes: "Hinged rectangular travel luggage" },
    { word: "Lighter", category: "Everyday Objects", difficulty: "medium", aliases: ["lighters"], forbiddenVariants: ["spark flame starter"], compoundVariants: [], notes: "Handheld spark flame ignition device" },
    { word: "Headphones", category: "Everyday Objects", difficulty: "medium", aliases: ["headset", "earphones"], forbiddenVariants: ["over ear audio"], compoundVariants: ["head phones"], notes: "Ear-cup sound speakers" },
    { word: "Broom", category: "Everyday Objects", difficulty: "easy", aliases: ["brooms", "sweeper"], forbiddenVariants: ["bristle brush sweep"], compoundVariants: [], notes: "Long-handled floor sweeper" },
    { word: "Bucket", category: "Everyday Objects", difficulty: "easy", aliases: ["buckets", "pail"], forbiddenVariants: ["handled water vessel"], compoundVariants: [], notes: "Open cylindrical container with handle" },
    { word: "Keyboard", category: "Everyday Objects", difficulty: "easy", aliases: ["keyboards"], forbiddenVariants: ["typing buttons"], compoundVariants: [], notes: "Input board with keys" },
    { word: "Fork", category: "Everyday Objects", difficulty: "easy", aliases: ["forks"], forbiddenVariants: ["pronged utensil"], compoundVariants: [], notes: "Pronged dining instrument" },
    { word: "Plate", category: "Everyday Objects", difficulty: "easy", aliases: ["plates", "dish"], forbiddenVariants: ["dining dish"], compoundVariants: [], notes: "Flat circular meal dish" },
    { word: "MagnifyingGlass", category: "Everyday Objects", difficulty: "medium", aliases: ["magnifier", "magnifying glass"], forbiddenVariants: ["zoom glass"], compoundVariants: ["magnifying glass"], notes: "Convex lens with handle" },
    { word: "Envelope", category: "Everyday Objects", difficulty: "medium", aliases: ["envelopes"], forbiddenVariants: ["letter paper holder"], compoundVariants: [], notes: "Folded flat paper packet for mail" }
  ],

  "Places & Travel": [
    { word: "Airport", category: "Places & Travel", difficulty: "easy", aliases: ["airports", "airfield"], forbiddenVariants: ["plane runway terminal"], compoundVariants: ["air port"], notes: "Aviation terminal and runways" },
    { word: "Beach", category: "Places & Travel", difficulty: "easy", aliases: ["beaches", "shoreline"], forbiddenVariants: ["sandy coast"], compoundVariants: [], notes: "Sandy ocean water's edge" },
    { word: "Hotel", category: "Places & Travel", difficulty: "easy", aliases: ["hotels", "motel"], forbiddenVariants: ["guest overnight inn"], compoundVariants: [], notes: "Commercial lodging establishment" },
    { word: "Library", category: "Places & Travel", difficulty: "easy", aliases: ["libraries"], forbiddenVariants: ["book depository"], compoundVariants: [], notes: "Public collection of books" },
    { word: "ArtGallery", category: "Places & Travel", difficulty: "easy", aliases: ["art exhibition", "art museum"], forbiddenVariants: ["framed painting exhibition"], compoundVariants: ["art gallery"], notes: "Public hall displaying visual artworks" },
    { word: "Hospital", category: "Places & Travel", difficulty: "easy", aliases: ["hospitals", "infirmary"], forbiddenVariants: ["medical emergency center"], compoundVariants: [], notes: "Institution for patient medical care" },
    { word: "Museum", category: "Places & Travel", difficulty: "easy", aliases: ["museums", "gallery"], forbiddenVariants: ["historical exhibit hall"], compoundVariants: [], notes: "Building housing historical artifacts" },
    { word: "Restaurant", category: "Places & Travel", difficulty: "easy", aliases: ["eatery", "bistro"], forbiddenVariants: ["prepared table meal venue"], compoundVariants: [], notes: "Establishment serving prepared meals" },
    { word: "Subway", category: "Places & Travel", difficulty: "easy", aliases: ["metro", "underground train"], forbiddenVariants: ["underground rail transit"], compoundVariants: [], notes: "Underground electric railway" },
    { word: "Bakery", category: "Places & Travel", difficulty: "easy", aliases: ["bakeries"], forbiddenVariants: ["fresh bread shop"], compoundVariants: [], notes: "Establishment producing baked goods" },
    { word: "Campground", category: "Places & Travel", difficulty: "easy", aliases: ["campgrounds"], forbiddenVariants: ["outdoor tent grounds"], compoundVariants: ["camp ground"], notes: "Outdoor leisure area for pitching tents" },
    { word: "Aquarium", category: "Places & Travel", difficulty: "medium", aliases: ["aquariums"], forbiddenVariants: ["fish tank facility"], compoundVariants: [], notes: "Public marine life display tanks" },
    { word: "Castle", category: "Places & Travel", difficulty: "medium", aliases: ["castles", "fortress"], forbiddenVariants: ["medieval stone stronghold"], compoundVariants: [], notes: "Fortified stone medieval residence" },
    { word: "Lighthouse", category: "Places & Travel", difficulty: "medium", aliases: ["beacon"], forbiddenVariants: ["coastal light tower"], compoundVariants: ["light house"], notes: "Tower with rotating optical beacon" },
    { word: "Stadium", category: "Places & Travel", difficulty: "medium", aliases: ["arena", "stadiums"], forbiddenVariants: ["sports arena bowl"], compoundVariants: [], notes: "Large tiered sporting arena" },
    { word: "Pharmacy", category: "Places & Travel", difficulty: "medium", aliases: ["drugstore", "chemist"], forbiddenVariants: ["prescription counter"], compoundVariants: [], notes: "Dispensary of medical prescriptions" },
    { word: "Casino", category: "Places & Travel", difficulty: "medium", aliases: ["casinos"], forbiddenVariants: ["gambling floor hall"], compoundVariants: [], notes: "Gaming establishment with table games" },
    { word: "Skyscraper", category: "Places & Travel", difficulty: "medium", aliases: ["high-rise"], forbiddenVariants: ["tall city tower"], compoundVariants: ["sky scraper"], notes: "Very tall multi-story building" },
    { word: "Observatory", category: "Places & Travel", difficulty: "medium", aliases: ["astronomical observatory"], forbiddenVariants: ["dome telescope"], compoundVariants: [], notes: "Dome housing optical telescope" },
    { word: "Cathedral", category: "Places & Travel", difficulty: "medium", aliases: ["basilica"], forbiddenVariants: ["large church sanctuary"], compoundVariants: [], notes: "Principal episcopal church building" },
    { word: "Submarine", category: "Places & Travel", difficulty: "medium", aliases: ["sub", "submersibles"], forbiddenVariants: ["underwater warship"], compoundVariants: [], notes: "Underwater naval vessel" },
    { word: "Cemetery", category: "Places & Travel", difficulty: "medium", aliases: ["graveyard"], forbiddenVariants: ["burial grounds"], compoundVariants: [], notes: "Burial ground with headstones" },
    { word: "Harbor", category: "Places & Travel", difficulty: "medium", aliases: ["harbour", "seaport"], forbiddenVariants: ["docked ship bay"], compoundVariants: [], notes: "Sheltered coastal water for anchoring ships" },
    { word: "Zoo", category: "Places & Travel", difficulty: "easy", aliases: ["zoos", "safari park"], forbiddenVariants: ["animal cages"], compoundVariants: [], notes: "Enclosed park displaying live animals" },
    { word: "School", category: "Places & Travel", difficulty: "easy", aliases: ["schools", "academy"], forbiddenVariants: ["classroom campus"], compoundVariants: [], notes: "Institution for educating students" },
    { word: "Cinema", category: "Places & Travel", difficulty: "easy", aliases: ["movie theater"], forbiddenVariants: ["film screen auditorium"], compoundVariants: [], notes: "Auditorium for projecting motion pictures" },
    { word: "Bank", category: "Places & Travel", difficulty: "easy", aliases: ["banks"], forbiddenVariants: ["cash deposit vault"], compoundVariants: [], notes: "Financial depository institution" },
    { word: "PostOffice", category: "Places & Travel", difficulty: "easy", aliases: ["post office"], forbiddenVariants: ["mail parcel desk"], compoundVariants: ["post office"], notes: "Local postal facility for sending mail" },
    { word: "GasStation", category: "Places & Travel", difficulty: "easy", aliases: ["gas station", "petrol station"], forbiddenVariants: ["roadside fuel pump"], compoundVariants: ["gas station"], notes: "Retail station selling motor fuel" },
    { word: "TrainStation", category: "Places & Travel", difficulty: "medium", aliases: ["railway depot"], forbiddenVariants: ["train track depot"], compoundVariants: ["train station"], notes: "Terminal stopping place for railway trains" },
    { word: "PoliceStation", category: "Places & Travel", difficulty: "medium", aliases: ["precinct", "police station"], forbiddenVariants: ["law enforcement station"], compoundVariants: ["police station"], notes: "Headquarters for local police officers" },
    { word: "Firehouse", category: "Places & Travel", difficulty: "medium", aliases: ["fire station"], forbiddenVariants: ["fire truck engine garage"], compoundVariants: ["fire house"], notes: "Garage station for firefighting vehicles" },
    { word: "Nightclub", category: "Places & Travel", difficulty: "medium", aliases: ["dance club", "night club"], forbiddenVariants: ["midnight dance floor"], compoundVariants: ["night club"], notes: "Late night entertainment dance venue" },
    { word: "Gymnasium", category: "Places & Travel", difficulty: "easy", aliases: ["gym"], forbiddenVariants: ["indoor workout court"], compoundVariants: [], notes: "Indoor hall equipped for physical exercise" },
    { word: "Carnival", category: "Places & Travel", difficulty: "medium", aliases: ["carnivals", "fairground"], forbiddenVariants: ["traveling Ferris wheel show"], compoundVariants: [], notes: "Traveling amusement show with rides" },
    { word: "Monastery", category: "Places & Travel", difficulty: "medium", aliases: ["monasteries", "abbey"], forbiddenVariants: ["monk sanctuary cloister"], compoundVariants: [], notes: "Residence for religious monastic orders" },
    { word: "Laundromat", category: "Places & Travel", difficulty: "medium", aliases: ["laundrette"], forbiddenVariants: ["coin washing machines"], compoundVariants: [], notes: "Coin-operated self-service laundry" }
  ],

  "Sports & Activities": [
    { word: "Soccer", category: "Sports & Activities", difficulty: "easy", aliases: ["football", "association football"], forbiddenVariants: ["eleven player kicking"], compoundVariants: [], notes: "Team sport kicking a spherical ball" },
    { word: "Basketball", category: "Sports & Activities", difficulty: "easy", aliases: ["hoops"], forbiddenVariants: ["bouncing ball into hoop"], compoundVariants: ["basket ball"], notes: "Sport aiming through elevated basket hoop" },
    { word: "Tennis", category: "Sports & Activities", difficulty: "easy", aliases: ["lawn tennis"], forbiddenVariants: ["racket net volley"], compoundVariants: [], notes: "Racket sport hitting across court net" },
    { word: "Wrestling", category: "Sports & Activities", difficulty: "easy", aliases: ["grappling"], forbiddenVariants: ["pinned on canvas mat"], compoundVariants: [], notes: "Hand-to-hand combat sport pinning opponents on mats" },
    { word: "Golf", category: "Sports & Activities", difficulty: "easy", aliases: ["golfing"], forbiddenVariants: ["club tee fairway green"], compoundVariants: [], notes: "Club game putting into 18 holes" },
    { word: "Swimming", category: "Sports & Activities", difficulty: "easy", aliases: ["swim"], forbiddenVariants: ["pool stroke water race"], compoundVariants: [], notes: "Propelling body through water strokes" },
    { word: "Bowling", category: "Sports & Activities", difficulty: "easy", aliases: ["ten pin"], forbiddenVariants: ["heavy ball rolling at pins"], compoundVariants: [], notes: "Rolling heavy ball down lane into pins" },
    { word: "Cycling", category: "Sports & Activities", difficulty: "easy", aliases: ["cyclist", "velo"], forbiddenVariants: ["pedaling wheels"], compoundVariants: [], notes: "Riding and racing bicycles" },
    { word: "Boxing", category: "Sports & Activities", difficulty: "easy", aliases: ["prizefighting"], forbiddenVariants: ["gloved ring punching match"], compoundVariants: [], notes: "Combat sport fighting with padded gloves" },
    { word: "Volleyball", category: "Sports & Activities", difficulty: "easy", aliases: ["beach volleyball"], forbiddenVariants: ["spiking ball over net"], compoundVariants: ["volley ball"], notes: "Hands-only team sport over high net" },
    { word: "Skiing", category: "Sports & Activities", difficulty: "easy", aliases: ["downhill skiing"], forbiddenVariants: ["snow slope gliders"], compoundVariants: [], notes: "Gliding across snow on long narrow runners" },
    { word: "Fishing", category: "Sports & Activities", difficulty: "easy", aliases: ["angling"], forbiddenVariants: ["catching fish hook rod"], compoundVariants: [], notes: "Catching fish with baited rod and line" },
    { word: "Hiking", category: "Sports & Activities", difficulty: "easy", aliases: ["trail walking"], forbiddenVariants: ["trail trekking on foot"], compoundVariants: [], notes: "Long distance cross-country trail walking" },
    { word: "Skateboarding", category: "Sports & Activities", difficulty: "easy", aliases: ["skating", "skate"], forbiddenVariants: ["four wheel board ollie"], compoundVariants: ["skate boarding"], notes: "Riding wheeled deck performing tricks" },
    { word: "Surfing", category: "Sports & Activities", difficulty: "easy", aliases: ["wave riding"], forbiddenVariants: ["riding ocean breakers"], compoundVariants: [], notes: "Riding breaking ocean waves on board" },
    { word: "Dodgeball", category: "Sports & Activities", difficulty: "easy", aliases: ["dodge ball"], forbiddenVariants: ["throwing rubber balls"], compoundVariants: ["dodge ball"], notes: "Throwing inflated balls at opponents" },
    { word: "Yoga", category: "Sports & Activities", difficulty: "easy", aliases: ["vinyasa"], forbiddenVariants: ["mat postures breathing"], compoundVariants: [], notes: "Spiritual and physical posture practice" },
    { word: "Cricket", category: "Sports & Activities", difficulty: "medium", aliases: ["test cricket"], forbiddenVariants: ["wicket pitch batting"], compoundVariants: [], notes: "Bat-and-ball match centered on wickets" },
    { word: "Rugby", category: "Sports & Activities", difficulty: "medium", aliases: ["rugby union"], forbiddenVariants: ["oval ball tackle sport"], compoundVariants: [], notes: "Collision game running with oval ball" },
    { word: "Badminton", category: "Sports & Activities", difficulty: "medium", aliases: ["shuttlecock game"], forbiddenVariants: ["feathered birdie racket"], compoundVariants: [], notes: "Racket sport hitting feathered shuttlecock" },
    { word: "Snowboarding", category: "Sports & Activities", difficulty: "medium", aliases: ["snowboard"], forbiddenVariants: ["single deck powder glide"], compoundVariants: ["snow boarding"], notes: "Downhill sliding strapped to single board" },
    { word: "Gymnastics", category: "Sports & Activities", difficulty: "medium", aliases: ["acrobatics"], forbiddenVariants: ["balance beam vaulting"], compoundVariants: [], notes: "Acrobatic exercises demonstrating balance" },
    { word: "Archery", category: "Sports & Activities", difficulty: "medium", aliases: ["bowhunting"], forbiddenVariants: ["bow and arrow target"], compoundVariants: [], notes: "Shooting arrows with bow at target" },
    { word: "Rowing", category: "Sports & Activities", difficulty: "medium", aliases: ["crew racing"], forbiddenVariants: ["oared boat river race"], compoundVariants: [], notes: "Propelling racing shell with oars" },
    { word: "RockClimbing", category: "Sports & Activities", difficulty: "medium", aliases: ["bouldering", "rock climbing"], forbiddenVariants: ["scaling cliff harness"], compoundVariants: ["rock climbing"], notes: "Scaling sheer vertical natural rock faces" },
    { word: "Karate", category: "Sports & Activities", difficulty: "medium", aliases: ["martial art"], forbiddenVariants: ["white gi punching kicks"], compoundVariants: [], notes: "Striking martial art from Okinawa" },
    { word: "ScubaDiving", category: "Sports & Activities", difficulty: "medium", aliases: ["scuba", "scuba diving"], forbiddenVariants: ["underwater air tank"], compoundVariants: ["scuba diving"], notes: "Underwater breathing apparatus swimming" },
    { word: "Kayaking", category: "Sports & Activities", difficulty: "medium", aliases: ["kayak"], forbiddenVariants: ["double bladed paddle boat"], compoundVariants: [], notes: "Paddling low-seated narrow boat" },
    { word: "Weightlifting", category: "Sports & Activities", difficulty: "medium", aliases: ["powerlifting"], forbiddenVariants: ["barbell clean and jerk"], compoundVariants: ["weight lifting"], notes: "Lifting barbells with weighted plates" },
    { word: "Billiards", category: "Sports & Activities", difficulty: "medium", aliases: ["pool game", "snooker"], forbiddenVariants: ["cue stick pocket balls"], compoundVariants: [], notes: "Cue sport on baize table with pockets" },
    { word: "Marathon", category: "Sports & Activities", difficulty: "medium", aliases: ["long distance run"], forbiddenVariants: ["twenty six mile race"], compoundVariants: [], notes: "Long-distance foot race of 26 miles" },
    { word: "Curling", category: "Sports & Activities", difficulty: "medium", aliases: ["sheet curling"], forbiddenVariants: ["sliding stone broom sweeping"], compoundVariants: [], notes: "Sliding granite stones on ice sheet" },
    { word: "Fencing", category: "Sports & Activities", difficulty: "medium", aliases: ["swordplay"], forbiddenVariants: ["foil thrusting duel"], compoundVariants: [], notes: "Combat sport fighting with slender foils" },
    { word: "Polo", category: "Sports & Activities", difficulty: "medium", aliases: ["horse polo"], forbiddenVariants: ["horseback mallet field game"], compoundVariants: [], notes: "Horseback game hitting ball with mallets" },
    { word: "Triathlon", category: "Sports & Activities", difficulty: "medium", aliases: ["triathlete"], forbiddenVariants: ["swim bike and run"], compoundVariants: [], notes: "Multi-sport race of swim, cycle, run" },
    { word: "Parkour", category: "Sports & Activities", difficulty: "medium", aliases: ["freerunning"], forbiddenVariants: ["urban obstacle vaulting"], compoundVariants: [], notes: "Navigating urban obstacles by vaulting" },
    { word: "TableTennis", category: "Sports & Activities", difficulty: "easy", aliases: ["ping pong", "table tennis"], forbiddenVariants: ["paddle ball rebound table"], compoundVariants: ["table tennis", "ping pong"], notes: "Paddle ball game over miniature table net" }
  ],

  "Jobs & Occupations": [
    { word: "Doctor", category: "Jobs & Occupations", difficulty: "easy", aliases: ["physician"], forbiddenVariants: ["medical stethoscope"], compoundVariants: [], notes: "Licensed practitioner of medicine" },
    { word: "Teacher", category: "Jobs & Occupations", difficulty: "easy", aliases: ["educator", "instructor"], forbiddenVariants: ["classroom instructor"], compoundVariants: [], notes: "Educator instructing students in school" },
    { word: "Chef", category: "Jobs & Occupations", difficulty: "easy", aliases: ["cook"], forbiddenVariants: ["kitchen culinary master"], compoundVariants: [], notes: "Professional culinary head in restaurant" },
    { word: "PoliceOfficer", category: "Jobs & Occupations", difficulty: "easy", aliases: ["cop", "police officer"], forbiddenVariants: ["badge patrol car"], compoundVariants: ["police officer"], notes: "Warranted officer enforcing civil law" },
    { word: "Firefighter", category: "Jobs & Occupations", difficulty: "easy", aliases: ["fireman"], forbiddenVariants: ["hose engine fire crew"], compoundVariants: ["fire fighter"], notes: "Rescuer extinguishing destructive fires" },
    { word: "Pilot", category: "Jobs & Occupations", difficulty: "easy", aliases: ["aviator"], forbiddenVariants: ["cockpit airplane steering"], compoundVariants: [], notes: "Operator steering aircraft controls" },
    { word: "Dentist", category: "Jobs & Occupations", difficulty: "easy", aliases: ["orthodontist"], forbiddenVariants: ["drilling teeth in chair"], compoundVariants: [], notes: "Doctor treating teeth and oral cavities" },
    { word: "Nurse", category: "Jobs & Occupations", difficulty: "easy", aliases: ["caregiver"], forbiddenVariants: ["hospital vital signs caregiver"], compoundVariants: [], notes: "Healthcare professional tending patients" },
    { word: "Astronaut", category: "Jobs & Occupations", difficulty: "easy", aliases: ["cosmonaut"], forbiddenVariants: ["rocket spacesuit voyager"], compoundVariants: [], notes: "Crew member on spacecraft missions" },
    { word: "Artist", category: "Jobs & Occupations", difficulty: "easy", aliases: ["painter"], forbiddenVariants: ["canvas brush creative"], compoundVariants: [], notes: "Creator producing visual artwork" },
    { word: "Farmer", category: "Jobs & Occupations", difficulty: "easy", aliases: ["cultivator"], forbiddenVariants: ["crop tractor agriculturalist"], compoundVariants: [], notes: "Cultivator managing crops and livestock" },
    { word: "Singer", category: "Jobs & Occupations", difficulty: "easy", aliases: ["vocalist"], forbiddenVariants: ["microphone vocal artist"], compoundVariants: [], notes: "Performer producing musical vocal sounds" },
    { word: "Actor", category: "Jobs & Occupations", difficulty: "easy", aliases: ["actress"], forbiddenVariants: ["stage script character player"], compoundVariants: [], notes: "Dramatic performer in theatre and film" },
    { word: "Photographer", category: "Jobs & Occupations", difficulty: "easy", aliases: ["cameraman"], forbiddenVariants: ["camera shutter portrait shooter"], compoundVariants: [], notes: "Specialist taking photographic pictures" },
    { word: "Barber", category: "Jobs & Occupations", difficulty: "easy", aliases: ["hair stylist"], forbiddenVariants: ["clipping shear hair trimmer"], compoundVariants: [], notes: "Hairdresser trimming hair and beards" },
    { word: "Miner", category: "Jobs & Occupations", difficulty: "easy", aliases: ["coal miner"], forbiddenVariants: ["pickaxe underground quarry worker"], compoundVariants: ["coal miner"], notes: "Worker extracting mineral deposits underground" },
    { word: "Carpenter", category: "Jobs & Occupations", difficulty: "medium", aliases: ["woodworker"], forbiddenVariants: ["wood sawing hammer joiner"], compoundVariants: [], notes: "Craftsman building structural woodwork" },
    { word: "Judge", category: "Jobs & Occupations", difficulty: "easy", aliases: ["magistrate"], forbiddenVariants: ["gavel courtroom bench"], compoundVariants: [], notes: "Public official presiding over law courts" },
    { word: "Waiter", category: "Jobs & Occupations", difficulty: "easy", aliases: ["server", "waitress"], forbiddenVariants: ["table service food tray"], compoundVariants: [], notes: "Attendant taking orders at dining tables" },
    { word: "Detective", category: "Jobs & Occupations", difficulty: "medium", aliases: ["investigator", "sleuth"], forbiddenVariants: ["clue solver crime investigator"], compoundVariants: [], notes: "Investigator gathering crime evidence" },
    { word: "Librarian", category: "Jobs & Occupations", difficulty: "medium", aliases: ["archivist"], forbiddenVariants: ["catalog book keeper"], compoundVariants: [], notes: "Custodian managing library collections" },
    { word: "Mechanic", category: "Jobs & Occupations", difficulty: "medium", aliases: ["auto technician"], forbiddenVariants: ["wrench engine repairer"], compoundVariants: [], notes: "Tradesman repairing vehicular machinery" },
    { word: "Electrician", category: "Jobs & Occupations", difficulty: "medium", aliases: ["sparky"], forbiddenVariants: ["circuit wiring fuse worker"], compoundVariants: [], notes: "Tradesperson installing power wiring" },
    { word: "Plumber", category: "Jobs & Occupations", difficulty: "medium", aliases: ["pipefitter"], forbiddenVariants: ["pipe wrench leak specialist"], compoundVariants: [], notes: "Fitter installing water piping fixtures" },
    { word: "Architect", category: "Jobs & Occupations", difficulty: "medium", aliases: ["building designer"], forbiddenVariants: ["blueprint drafting planner"], compoundVariants: [], notes: "Designer drawing structural blueprints" },
    { word: "Lawyer", category: "Jobs & Occupations", difficulty: "medium", aliases: ["attorney"], forbiddenVariants: ["courtroom legal defender"], compoundVariants: [], notes: "Legal counsel practicing before courts" },
    { word: "Journalist", category: "Jobs & Occupations", difficulty: "medium", aliases: ["reporter"], forbiddenVariants: ["news headline writer"], compoundVariants: [], notes: "Writer reporting news for media" },
    { word: "Scientist", category: "Jobs & Occupations", difficulty: "medium", aliases: ["researcher"], forbiddenVariants: ["laboratory experimenter"], compoundVariants: [], notes: "Investigator conducting systematic research" },
    { word: "FlightAttendant", category: "Jobs & Occupations", difficulty: "medium", aliases: ["steward", "flight attendant"], forbiddenVariants: ["airplane cabin service"], compoundVariants: ["flight attendant"], notes: "Cabin crew ensuring passenger safety" },
    { word: "Veterinarian", category: "Jobs & Occupations", difficulty: "medium", aliases: ["vet"], forbiddenVariants: ["animal hospital doctor"], compoundVariants: [], notes: "Physician treating diseases in animals" },
    { word: "Lifeguard", category: "Jobs & Occupations", difficulty: "medium", aliases: ["beach guard"], forbiddenVariants: ["pool tower rescue swimmer"], compoundVariants: ["life guard"], notes: "Rescue swimmer protecting water visitors" },
    { word: "Florist", category: "Jobs & Occupations", difficulty: "medium", aliases: ["flower seller"], forbiddenVariants: ["stem clipping bouquet maker"], compoundVariants: [], notes: "Arranger and seller of cut flowers" },
    { word: "Bartender", category: "Jobs & Occupations", difficulty: "medium", aliases: ["mixologist", "barman"], forbiddenVariants: ["counter cocktail shaker"], compoundVariants: ["bar tender"], notes: "Server pouring beverages behind bar" },
    { word: "SecurityGuard", category: "Jobs & Occupations", difficulty: "medium", aliases: ["watchman", "security guard"], forbiddenVariants: ["night desk surveillance"], compoundVariants: ["security guard"], notes: "Guard maintaining patrol surveillance" },
    { word: "Paramedic", category: "Jobs & Occupations", difficulty: "medium", aliases: ["emt"], forbiddenVariants: ["ambulance siren emergency responder"], compoundVariants: [], notes: "Emergency responder on ambulances" },
    { word: "Tailor", category: "Jobs & Occupations", difficulty: "medium", aliases: ["seamstress"], forbiddenVariants: ["needle suit stitcher"], compoundVariants: [], notes: "Specialist sewing and fitting garments" },
    { word: "Blacksmith", category: "Jobs & Occupations", difficulty: "medium", aliases: ["smith"], forbiddenVariants: ["anvil hammer forge worker"], compoundVariants: ["black smith"], notes: "Craftsman forging wrought iron on anvils" }
  ],

  "Nature & Outdoors": [
    { word: "Forest", category: "Nature & Outdoors", difficulty: "easy", aliases: ["woods", "woodland"], forbiddenVariants: ["dense tree canopy"], compoundVariants: [], notes: "Large tract covered with dense trees" },
    { word: "Mountain", category: "Nature & Outdoors", difficulty: "easy", aliases: ["peak", "summit"], forbiddenVariants: ["rocky peak elevation"], compoundVariants: [], notes: "Large natural elevation of rock earth" },
    { word: "River", category: "Nature & Outdoors", difficulty: "easy", aliases: ["stream"], forbiddenVariants: ["flowing freshwater current"], compoundVariants: [], notes: "Natural flowing freshwater course" },
    { word: "Desert", category: "Nature & Outdoors", difficulty: "easy", aliases: ["arid wasteland"], forbiddenVariants: ["sand dune wasteland"], compoundVariants: [], notes: "Dry barren land with sparse rain" },
    { word: "Waterfall", category: "Nature & Outdoors", difficulty: "easy", aliases: ["cascade"], forbiddenVariants: ["cascading water drop"], compoundVariants: ["water fall"], notes: "Cascade of water over vertical precipice" },
    { word: "Rainbow", category: "Nature & Outdoors", difficulty: "easy", aliases: ["sky prism"], forbiddenVariants: ["multicolor prism arc"], compoundVariants: ["rain bow"], notes: "Meteorological optical colored arc in sky" },
    { word: "Volcano", category: "Nature & Outdoors", difficulty: "easy", aliases: ["eruption crater"], forbiddenVariants: ["molten magma cone"], compoundVariants: [], notes: "Vent in crust erupting molten lava" },
    { word: "Island", category: "Nature & Outdoors", difficulty: "easy", aliases: ["isle"], forbiddenVariants: ["isolated land in water"], compoundVariants: [], notes: "Land mass entirely encircled by water" },
    { word: "Cave", category: "Nature & Outdoors", difficulty: "easy", aliases: ["cavern", "grotto"], forbiddenVariants: ["underground rock chamber"], compoundVariants: [], notes: "Natural subterranean hollow chamber" },
    { word: "Sunset", category: "Nature & Outdoors", difficulty: "easy", aliases: ["dusk", "sundown"], forbiddenVariants: ["evening solar horizon"], compoundVariants: ["sun set"], notes: "Daily disappearance of sun beneath horizon" },
    { word: "Thunderstorm", category: "Nature & Outdoors", difficulty: "easy", aliases: ["tempest"], forbiddenVariants: ["lightning rain cloudburst"], compoundVariants: ["thunder storm"], notes: "Storm with lightning and thunder" },
    { word: "Snowflake", category: "Nature & Outdoors", difficulty: "easy", aliases: ["snow crystal"], forbiddenVariants: ["six pointed ice crystal"], compoundVariants: ["snow flake"], notes: "Symmetrical ice crystal falling as snow" },
    { word: "Tornado", category: "Nature & Outdoors", difficulty: "easy", aliases: ["twister", "cyclone"], forbiddenVariants: ["rotating wind funnel"], compoundVariants: [], notes: "Violently rotating column of air" },
    { word: "Earthquake", category: "Nature & Outdoors", difficulty: "easy", aliases: ["tremor"], forbiddenVariants: ["tectonic ground shaking"], compoundVariants: ["earth quake"], notes: "Shaking of ground from fault movement" },
    { word: "Ocean", category: "Nature & Outdoors", difficulty: "easy", aliases: ["sea"], forbiddenVariants: ["vast saltwater expanse"], compoundVariants: [], notes: "Vast body of interconnected salt water" },
    { word: "Lake", category: "Nature & Outdoors", difficulty: "easy", aliases: ["lagoon water"], forbiddenVariants: ["inland water basin"], compoundVariants: [], notes: "Inland body of water enclosed by land" },
    { word: "Campfire", category: "Nature & Outdoors", difficulty: "easy", aliases: ["bonfire"], forbiddenVariants: ["outdoor burning logs"], compoundVariants: ["camp fire"], notes: "Outdoor stone ring wood fire" },
    { word: "Cloud", category: "Nature & Outdoors", difficulty: "easy", aliases: ["clouds"], forbiddenVariants: ["condensed sky vapor"], compoundVariants: [], notes: "Visible mass of condensed water droplets" },
    { word: "Sunrise", category: "Nature & Outdoors", difficulty: "easy", aliases: ["daybreak", "dawn"], forbiddenVariants: ["morning solar rise"], compoundVariants: ["sun rise"], notes: "Daily morning ascent of sun above horizon" },
    { word: "Glacier", category: "Nature & Outdoors", difficulty: "medium", aliases: ["ice sheet"], forbiddenVariants: ["slow moving ice pack"], compoundVariants: [], notes: "Massive slow-moving river of dense ice" },
    { word: "CoralReef", category: "Nature & Outdoors", difficulty: "medium", aliases: ["barrier reef", "coral reef"], forbiddenVariants: ["underwater calcareous colony"], compoundVariants: ["coral reef"], notes: "Marine ridge formed by calcium carbonate" },
    { word: "Canyon", category: "Nature & Outdoors", difficulty: "medium", aliases: ["gorge", "ravine"], forbiddenVariants: ["steep carved plateau gorge"], compoundVariants: [], notes: "Deep gorge between towering cliffs" },
    { word: "Swamp", category: "Nature & Outdoors", difficulty: "medium", aliases: ["marsh", "wetland"], forbiddenVariants: ["muddy mangrove wetland"], compoundVariants: [], notes: "Forested wetland inundated by water" },
    { word: "Jungle", category: "Nature & Outdoors", difficulty: "medium", aliases: ["rainforest"], forbiddenVariants: ["dense tropical vine woods"], compoundVariants: [], notes: "Dense tropical vegetation forest" },
    { word: "Geyser", category: "Nature & Outdoors", difficulty: "medium", aliases: ["hot spring spout"], forbiddenVariants: ["pressurized boiling mineral spout"], compoundVariants: [], notes: "Intermittent boiling water spring spout" },
    { word: "Tundra", category: "Nature & Outdoors", difficulty: "medium", aliases: ["arctic plain"], forbiddenVariants: ["treeless frozen subsoil"], compoundVariants: [], notes: "Treeless arctic plain with permafrost" },
    { word: "Avalanche", category: "Nature & Outdoors", difficulty: "medium", aliases: ["snowslide"], forbiddenVariants: ["mountain snow crest collapse"], compoundVariants: [], notes: "Rapid slide of snow down mountain slope" },
    { word: "Oasis", category: "Nature & Outdoors", difficulty: "medium", aliases: ["desert spring"], forbiddenVariants: ["fertile palm water spot"], compoundVariants: [], notes: "Isolated spring-fed fertile area in desert" },
    { word: "Cliff", category: "Nature & Outdoors", difficulty: "medium", aliases: ["precipice", "crag"], forbiddenVariants: ["vertical rock face drop"], compoundVariants: [], notes: "Steep high rock face drop-off" },
    { word: "Valley", category: "Nature & Outdoors", difficulty: "medium", aliases: ["glen", "dale"], forbiddenVariants: ["low gap between mountain ridges"], compoundVariants: [], notes: "Elongated depression between hills" },
    { word: "Meadow", category: "Nature & Outdoors", difficulty: "medium", aliases: ["pasture"], forbiddenVariants: ["wildflower open grassy clearing"], compoundVariants: [], notes: "Open grassland with blooming wildflowers" },
    { word: "Wildfire", category: "Nature & Outdoors", difficulty: "medium", aliases: ["forest fire", "bushfire"], forbiddenVariants: ["uncontrolled brush blaze"], compoundVariants: ["wild fire"], notes: "Uncontrolled sweeping woodland blaze" },
    { word: "Hailstorm", category: "Nature & Outdoors", difficulty: "medium", aliases: ["hail shower"], forbiddenVariants: ["falling frozen ice pellets"], compoundVariants: ["hail storm"], notes: "Convective storm precipitating ice pellets" },
    { word: "Lagoon", category: "Nature & Outdoors", difficulty: "medium", aliases: ["coastal pool"], forbiddenVariants: ["barrier reef enclosed pool"], compoundVariants: [], notes: "Shallow pool separated by reefs" },
    { word: "Stalactite", category: "Nature & Outdoors", difficulty: "medium", aliases: ["cave icicle"], forbiddenVariants: ["mineral cave ceiling spike"], compoundVariants: [], notes: "Tapering mineral formation hanging from cave" },
    { word: "SandDune", category: "Nature & Outdoors", difficulty: "medium", aliases: ["dune", "sand dune"], forbiddenVariants: ["windblown desert ridge"], compoundVariants: ["sand dune"], notes: "Wind-sculpted ridge of shifting sand" },
    { word: "MeteorShower", category: "Nature & Outdoors", difficulty: "medium", aliases: ["shooting stars", "meteor shower"], forbiddenVariants: ["celestial debris streak"], compoundVariants: ["meteor shower"], notes: "Atmospheric trail of vaporizing space debris" }
  ],

  "Daily Life & Routine": [
    { word: "Breakfast", category: "Daily Life & Routine", difficulty: "easy", aliases: ["morning meal"], forbiddenVariants: ["first morning toast plate"], compoundVariants: [], notes: "First meal of day breaking night fast" },
    { word: "Laundry", category: "Daily Life & Routine", difficulty: "easy", aliases: ["washing clothes"], forbiddenVariants: ["tumble detergent hamper"], compoundVariants: [], notes: "Washing and drying dirty clothing" },
    { word: "Shower", category: "Daily Life & Routine", difficulty: "easy", aliases: ["bathing"], forbiddenVariants: ["hot water spray stall"], compoundVariants: [], notes: "Bathing under sprayed water stream" },
    { word: "TrafficJam", category: "Daily Life & Routine", difficulty: "easy", aliases: ["gridlock", "traffic jam"], forbiddenVariants: ["bumper to bumper commute delay"], compoundVariants: ["traffic jam"], notes: "Roadway blockage of stalled motor vehicles" },
    { word: "GroceryStore", category: "Daily Life & Routine", difficulty: "easy", aliases: ["grocer", "grocery store"], forbiddenVariants: ["shopping cart checkout aisles"], compoundVariants: ["grocery store"], notes: "Retail market stocking packaged pantry foods" },
    { word: "Dishwasher", category: "Daily Life & Routine", difficulty: "easy", aliases: ["dish washer"], forbiddenVariants: ["racked soapy plate washing appliance"], compoundVariants: ["dish washer"], notes: "Kitchen appliance for cleaning dishware" },
    { word: "Haircut", category: "Daily Life & Routine", difficulty: "easy", aliases: ["trim"], forbiddenVariants: ["barber shear styling trim"], compoundVariants: ["hair cut"], notes: "Act of clipping and grooming hair" },
    { word: "Elevator", category: "Daily Life & Routine", difficulty: "easy", aliases: ["lift"], forbiddenVariants: ["vertical cable car lift"], compoundVariants: [], notes: "Cable car ascending vertically in building" },
    { word: "Bedtime", category: "Daily Life & Routine", difficulty: "easy", aliases: ["slumber time"], forbiddenVariants: ["mattress pillow sleep schedule"], compoundVariants: ["bed time"], notes: "Usual scheduled hour for retiring to sleep" },
    { word: "Flossing", category: "Daily Life & Routine", difficulty: "easy", aliases: ["dental floss"], forbiddenVariants: ["waxed string tooth clean"], compoundVariants: [], notes: "Cleaning interdental spaces with waxed string" },
    { word: "AlarmClock", category: "Daily Life & Routine", difficulty: "medium", aliases: ["alarm", "alarm clock"], forbiddenVariants: ["morning bell wake buzzer"], compoundVariants: ["alarm clock"], notes: "Horological device waking sleepers with sound" },
    { word: "Vacuuming", category: "Daily Life & Routine", difficulty: "medium", aliases: ["vacuum"], forbiddenVariants: ["suction carpet dust cleaner"], compoundVariants: [], notes: "Cleaning flooring with suction air pump" },
    { word: "Ironing", category: "Daily Life & Routine", difficulty: "medium", aliases: ["pressing clothes"], forbiddenVariants: ["heated soleplate wrinkle press"], compoundVariants: [], notes: "Smoothing fabric wrinkles with heated iron" },
    { word: "DogWalking", category: "Daily Life & Routine", difficulty: "medium", aliases: ["walking the dog", "dog walk"], forbiddenVariants: ["leashed pet sidewalk stroll"], compoundVariants: ["dog walking", "dog walk"], notes: "Exercising leashed pet on neighborhood route" },
    { word: "BillPaying", category: "Daily Life & Routine", difficulty: "medium", aliases: ["paying bills"], forbiddenVariants: ["utility invoice bank transfer"], compoundVariants: ["bill paying"], notes: "Remitting payment for recurring utility debts" },
    { word: "BedMaking", category: "Daily Life & Routine", difficulty: "medium", aliases: ["making the bed"], forbiddenVariants: ["tucking sheets smoothed duvet"], compoundVariants: ["bed making"], notes: "Arranging sheets neatly over sleeping mattress" },
    { word: "MidnightSnack", category: "Daily Life & Routine", difficulty: "medium", aliases: ["late night bite", "midnight snack"], forbiddenVariants: ["open fridge late pantry raid"], compoundVariants: ["midnight snack"], notes: "Eating light food during late night hours" },
    { word: "GroceryList", category: "Daily Life & Routine", difficulty: "medium", aliases: ["shopping list", "grocery list"], forbiddenVariants: ["written pantry purchase checklist"], compoundVariants: ["grocery list"], notes: "Written checklist of foods to purchase" },
    { word: "LunchPacking", category: "Daily Life & Routine", difficulty: "medium", aliases: ["packing lunch"], forbiddenVariants: ["sandwich lunchbox preparation"], compoundVariants: ["lunch packing"], notes: "Preparing mid-day boxed meal to take to work" },
    { word: "PhoneCharging", category: "Daily Life & Routine", difficulty: "medium", aliases: ["charging phone"], forbiddenVariants: ["plugging wall adapter battery cord"], compoundVariants: ["phone charging"], notes: "Connecting mobile battery to power outlet" },
    { word: "TableSetting", category: "Daily Life & Routine", difficulty: "medium", aliases: ["setting table"], forbiddenVariants: ["silverware plates napkin layout"], compoundVariants: ["table setting"], notes: "Arranging cutlery and dishes for dining" },
    { word: "QueueWaiting", category: "Daily Life & Routine", difficulty: "medium", aliases: ["waiting in line", "queuing"], forbiddenVariants: ["standing in queue line"], compoundVariants: [], notes: "Standing in sequential queue awaiting service" },
    { word: "CatNapping", category: "Daily Life & Routine", difficulty: "medium", aliases: ["power nap", "taking a nap"], forbiddenVariants: ["couch thirty minute afternoon snooze"], compoundVariants: [], notes: "Taking short restorative daytime sleep" },
    { word: "DoorUnlocking", category: "Daily Life & Routine", difficulty: "medium", aliases: ["unlocking door"], forbiddenVariants: ["key deadbolt cylinder turn"], compoundVariants: [], notes: "Inserting key to release deadbolt mechanism" },
    { word: "HandWashing", category: "Daily Life & Routine", difficulty: "easy", aliases: ["washing hands"], forbiddenVariants: ["twenty second lathering faucet soap"], compoundVariants: ["hand washing"], notes: "Scrubbing hands with soap and flowing water" },
    { word: "WindowCleaning", category: "Daily Life & Routine", difficulty: "medium", aliases: ["cleaning windows"], forbiddenVariants: ["spray squeegee glass swipe"], compoundVariants: ["window cleaning"], notes: "Wiping transparent window glass panes" },
    { word: "WeatherChecking", category: "Daily Life & Routine", difficulty: "medium", aliases: ["checking weather"], forbiddenVariants: ["smartphone barometer forecast check"], compoundVariants: [], notes: "Consulting meteorological forecast for day" },
    { word: "TrainCommute", category: "Daily Life & Routine", difficulty: "medium", aliases: ["commuter train", "train commute"], forbiddenVariants: ["turnstile card passenger rail travel"], compoundVariants: ["train commute"], notes: "Traveling to workplace by commuter rail" },
    { word: "LawnMowing", category: "Daily Life & Routine", difficulty: "medium", aliases: ["mowing lawn"], forbiddenVariants: ["rotary blade grass cutter"], compoundVariants: ["lawn mowing"], notes: "Trimming turfgrass with rotary machine" },
    { word: "SnoozeButton", category: "Daily Life & Routine", difficulty: "medium", aliases: ["snooze", "snooze button"], forbiddenVariants: ["nine minute alarm slap delay"], compoundVariants: ["snooze button"], notes: "Switch silencing alarm for brief respite" },
    { word: "GarbageTaking", category: "Daily Life & Routine", difficulty: "easy", aliases: ["taking out trash"], forbiddenVariants: ["curbside haul tied plastic bin"], compoundVariants: [], notes: "Moving waste receptacle bags to street curb" },
    { word: "PlantWatering", category: "Daily Life & Routine", difficulty: "easy", aliases: ["watering plants"], forbiddenVariants: ["watering can pouring soil"], compoundVariants: [], notes: "Hydrating indoor potted vegetation" },
    { word: "FaceWashing", category: "Daily Life & Routine", difficulty: "easy", aliases: ["washing face"], forbiddenVariants: ["splashing water facial cleansing"], compoundVariants: ["face washing"], notes: "Rinsing and cleansing facial skin at sink" },
    { word: "MailChecking", category: "Daily Life & Routine", difficulty: "easy", aliases: ["checking mail"], forbiddenVariants: ["metal curbside mailbox letters"], compoundVariants: ["mail checking"], notes: "Retrieving physical letters from post box" },
    { word: "ShoeLacing", category: "Daily Life & Routine", difficulty: "easy", aliases: ["tying shoes"], forbiddenVariants: ["knotting sneaker lace eyelets"], compoundVariants: [], notes: "Fastening footgear by knotting cords" },
    { word: "CarWashing", category: "Daily Life & Routine", difficulty: "medium", aliases: ["washing car"], forbiddenVariants: ["soap sponge driveway vehicle rinse"], compoundVariants: ["car washing"], notes: "Cleaning vehicle exterior body panels" },
    { word: "PassportRenewing", category: "Daily Life & Routine", difficulty: "medium", aliases: ["renewing passport"], forbiddenVariants: ["international travel booklet application"], compoundVariants: [], notes: "Applying for updated diplomatic travel booklet" }
  ]
};

module.exports = WORDS;
